[package]
name = "idioms"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.*", features = ["full"] }
rand = "0.8.*"
rsa = {version = "0.8.*", features=["pem"]}
aes-gcm-siv = "0.11.*"
 